### PR TITLE
Feat/On browser refresh or updating the file list dropdown new files will be loaded

### PR DESCRIPTION
**Pull request by JodyZ0203**
# Purpose

Fixes https://github.com/sweepai/sweep/issues/450

# Changes Made

Please provide a detailed list of the changes made in this pull request.

1. updated Gradio update event listener 

# Additional Notes

Please provide any additional notes or screenshots here.

https://github.com/sweepai/sweep/assets/56443135/09312231-0779-4683-b5c9-9770c3ce2263

### CODE REVIEW

**Comment by wwzeng1** [comment]
Thanks for the contribution! I'll look at this now

**Review by wwzeng1 — APPROVED** [review]
LGTM. This also works for me when running from source. I only have to check the pypa deployment/build, expect that by tonight

**Comment by JodyZ0203** [comment]
> LGTM. This also works for me when running from source. I only have to check the pypa deployment/build, expect that by tonight

Great! Thanks!

**Comment by kevinlu1248** [comment]
LGTM merging

**Comment by kevinlu1248** [comment]
@JodyZ0203 It's in 0.5.1

**Comment by JodyZ0203** [comment]
> @JodyZ0203 It's in 0.5.1

Let's goooo 🚀

**Pull request merged**
