### PR TITLE
Sweep: Update "tests/rerun_issue.py" to log traceback during exceptions

### PR DESCRIPTION
**Pull request by ayan-joshi**
# Purpose

This closes the issue #1896 

# Changes Made

Please provide a detailed list of the changes made in this pull request.

1. Used traceback to solve the issue 
2. Made changes in the code 

# Additional Notes

Implemented the traceback to solve the issue have a look 
@wwzeng1 @kevinlu1248

### CODE REVIEW

**Comment by kevinlu1248** [comment]
Why did you delete the `if` block?

This block:

```
    if i > 0:
        print(f"Waited for server to start ({i+1}s)")
```

**Comment by ayan-joshi** [comment]
> Why did you delete the `if` block?
> 
> This block:
> 
> ```
>     if i > 0:
>         print(f"Waited for server to start ({i+1}s)")
> ```

@kevinlu1248 I think it was the mistake I'll add it again otherwise it's fine with you ?

**Comment by ayan-joshi** [comment]
@kevinlu1248 made the changes

**Comment by kevinlu1248** [comment]
Indentation is still wrong and random missing newlines. Btw, these are for testing Sweep, not an actual ticket for humans to handle.

**Pull request closed without merging**
